#!/bin/bash
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
set -o errexit
set -o nounset
set -o pipefail

# Asserts that every jar we publish carries its licensing information in exactly
# one canonical place: META-INF/LICENSE and META-INF/NOTICE, both generated by
# maven-remote-resources-plugin and maven-shade-plugin's Apache transformers.
#
# This exists because the layout regressed silently across several releases
# (XTABLE-701): every jar shipped a second, differently named copy of the
# licensing information as META-INF/LICENSE-bundled and META-INF/NOTICE-bundled,
# and the shaded jars additionally carried each bundled dependency's own license
# file in whatever location that dependency happened to use, which made the
# licensing of a bundle very hard to review.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"

cd "${ROOT_DIR}"

# Entries a jar is allowed to carry. Anything else that looks like licensing
# information is a finding: it means the information is duplicated, or filed
# somewhere a reviewer will not think to look. META-INF/licenses/ is deliberately
# NOT allowed: the texts of non-Apache-2.0 licenses are inlined into
# META-INF/LICENSE so that a reviewer has exactly one file to read.
is_allowed_entry() {
  case "$1" in
    META-INF/LICENSE|META-INF/NOTICE|META-INF/DISCLAIMER|META-INF/DISCLAIMER-WIP|META-INF/DEPENDENCIES)
      return 0
      ;;
  esac
  return 1
}

discover_jars() {
  find . -type f -name '*.jar' 2>/dev/null \
    | grep -E '/target/[^/]+\.jar$' \
    | grep -vE '\-(sources|javadoc)\.jar$' \
    | grep -vE '/target/original-' \
    | sort
}

# Only the shaded modules, never the whole reactor: xtable-service needs a newer
# JDK than the one this runs under in CI, and it produces no shaded jar anyway.
# The "|| true" is on the grep alone, not on the pipeline or the caller: without
# it, a tree with no matching pom makes grep exit 1, errexit kills the script
# inside the command substitution, and the explicit "no modules" diagnostic below
# never prints. The caller still treats an empty result as a failure, so this
# cannot turn into the fail-open that made the previous gate a no-op.
shade_module_poms() {
  { grep -rl '<artifactId>maven-shade-plugin</artifactId>' --include=pom.xml . || true; } | sort
}

# The module directories, root excluded: the root pom carries the shade
# configuration in <pluginManagement> and builds no shaded jar of its own.
shade_module_dirs() {
  shade_module_poms \
    | xargs -n1 dirname \
    | sed -e 's|^\./||' -e '/^\.$/d' \
    | sort -u
}

shade_modules() {
  shade_module_dirs | paste -sd, -
}

# The artifactIds maven-shade-plugin is configured to bundle, read from the
# <artifactSet> block alone.
#
# Reading every <include> in the pom instead would work today and break the
# first time a shaded module gains an unrelated one - maven-surefire
# <includes>, a maven-resources <include>, a second shade execution filtering
# entries rather than artifacts. The failure would be reported as a licensing
# mismatch, which is the wrong place to start looking.
shade_artifact_set_includes() {
  awk '
    /<artifactSet>/  { in_set = 1 }
    /<\/artifactSet>/ { in_set = 0 }
    in_set && match($0, /<include>[^<]*<\/include>/) {
      print substr($0, RSTART + 9, RLENGTH - 19)
    }
  ' "$1"
}

# The bundled LICENSE is rendered by maven-remote-resources-plugin from the
# runtime dependency tree, filtered to <xtable.bundled.artifactIds>. That property
# has to mirror the module's maven-shade-plugin <artifactSet><includes>, because
# the runtime tree is a strict superset of what is actually bundled and listing
# the difference would describe components that are not in the jar - which is what
# XTABLE-701 objects to. Nothing but this check keeps the two in step, and drift
# between a shade include list and reality is exactly what XTABLE-880 records.
check_bundled_artifact_ids() {
  local status=0 module pom raw malformed includes declared
  while IFS= read -r pom; do
    module="$(dirname "${pom}" | sed 's|^\./||')"
    [[ "${module}" == "." ]] && continue

    raw="$(shade_artifact_set_includes "${pom}")"

    # Every shade <artifactSet><include> is a groupId:artifactId pattern. An
    # entry without a colon means the awk range above picked up something that
    # is not an artifact pattern, and stripping a groupId prefix from it would
    # silently produce a nonsense artifactId to compare against.
    malformed="$(printf '%s\n' "${raw}" | sed '/^$/d' | grep -v ':' || true)"
    if [[ -n "${malformed}" ]]; then
      echo "FAIL ${module}: <artifactSet> contains entries that are not groupId:artifactId patterns:"
      printf '  - %s\n' ${malformed}
      status=1
      continue
    fi

    includes="$(printf '%s\n' "${raw}" | sed -e '/^$/d' -e 's|^[^:]*:||' | sort -u | paste -sd, -)"
    declared="$(sed -n 's|.*<xtable.bundled.artifactIds>\([^<]*\)</xtable.bundled.artifactIds>.*|\1|p' "${pom}" \
      | tr ',' '\n' | sed '/^$/d' | sort -u | paste -sd, -)"

    if [[ -z "${includes}" ]]; then
      echo "FAIL ${module}: runs maven-shade-plugin but its <artifactSet> names no <include>."
      echo "  Nothing would constrain the generated LICENSE to the bundle."
      status=1
      continue
    fi

    if [[ -z "${declared}" ]]; then
      echo "FAIL ${module}: runs maven-shade-plugin but declares no <xtable.bundled.artifactIds>."
      echo "  Without it the generated LICENSE describes the whole runtime tree, not the bundle."
      status=1
      continue
    fi

    if [[ "${includes}" != "${declared}" ]]; then
      echo "FAIL ${module}: <xtable.bundled.artifactIds> does not mirror the shade <artifactSet><includes>."
      diff <(printf '%s\n' "${includes}" | tr ',' '\n') \
           <(printf '%s\n' "${declared}" | tr ',' '\n') \
        | sed -e 's|^<|  only in shade includes: |' -e 's|^>|  only in the property:    |' \
        | grep -E '^  only' || true
      status=1
    else
      echo "OK   ${module}: bundled artifactIds mirror the shade includes."
    fi
  done < <(shade_module_poms)
  return "${status}"
}

# The generated LICENSE reproduces the full text of every non-Apache-2.0 license
# its components are under. A dependency whose declared license the template does
# not recognise is emitted as an UNMAPPED-LICENSE line rather than quietly
# omitted, so that a dependency bump cannot ship a LICENSE that names a component
# without accounting for its terms.
check_unmapped_licenses() {
  local status=0 lic module entry coord allowlist expected
  allowlist="${ROOT_DIR}/release/license/bundled/unresolved-licenses.txt"

  # Assert the inputs exist before reading them. Scanning a set of generated
  # LICENSE files and reporting no findings is indistinguishable from scanning
  # none at all, so a module whose render was skipped - by
  # -Dxtable.bundled.resources.skip, by a -pl build that missed it, or by the
  # generate-sources execution being dropped - would take this gate green
  # without ever being looked at. That is the no-op the previous tooling
  # shipped with.
  while IFS= read -r expected; do
    if [[ ! -f "${expected}/target/bundled-archive-resources/META-INF/LICENSE" ]]; then
      echo "FAIL ${expected}: no generated bundled LICENSE at"
      echo "  ${expected}/target/bundled-archive-resources/META-INF/LICENSE"
      echo "  The module runs maven-shade-plugin, so maven-remote-resources-plugin should have"
      echo "  rendered one. Build it before checking: ./mvnw package -DskipTests -pl ${expected} -am"
      status=1
    fi
  done < <(shade_module_dirs)

  [[ ${status} -ne 0 ]] && return "${status}"

  while IFS= read -r lic; do
    module="$(echo "${lic}" | sed -e 's|^\./||' -e 's|/target/bundled-archive-resources/META-INF/LICENSE$||')"
    while IFS= read -r entry; do
      [[ -z "${entry}" ]] && continue
      coord="$(echo "${entry}" | sed -e 's|^UNMAPPED-LICENSE: ||' -e 's| -- .*$||')"
      # Match the coordinate against the first field only. unresolved-licenses.txt
      # documents its format as "coordinate <TAB or spaces> reason" and exists so
      # that every unresolved license carries a written record of what was
      # checked; a whole-line match would reject every entry written that way and
      # accept only a bare coordinate with the reason left off.
      if awk -v c="${coord}" '!/^[[:space:]]*#/ && $1 == c { found = 1 } END { exit !found }' \
           "${allowlist}" 2>/dev/null; then
        echo "WARN ${module}: ${coord} has no established license; allowed by unresolved-licenses.txt."
      else
        echo "FAIL ${module}: ${entry#UNMAPPED-LICENSE: }"
        echo "  Add a <supplement> to release/license/bundled/supplemental-models.xml naming"
        echo "  the license canonically, add its text to META-INF/LICENSE.vm if new, or - only"
        echo "  if the artifact genuinely does not say - record it in unresolved-licenses.txt."
        status=1
      fi
    done < <(grep '^UNMAPPED-LICENSE:' "${lic}" || true)
  done < <(find . -path '*/target/bundled-archive-resources/META-INF/LICENSE' -type f | sort)

  return "${status}"
}

jars=("$@")

if [[ ${#jars[@]} -eq 0 ]]; then
  while IFS= read -r jar; do
    jars+=("${jar}")
  done < <(discover_jars)
fi

if [[ ${#jars[@]} -eq 0 ]]; then
  modules="$(shade_modules)"
  if [[ -z "${modules}" ]]; then
    echo "FAIL: no modules with maven-shade-plugin were found. Refusing to pass without checking anything."
    exit 1
  fi
  echo "No jars found under */target, building the shaded modules first: ${modules}"
  ./mvnw -q package -B -DskipTests -Dmaven.build.cache.enabled=false -pl "${modules}" -am
  while IFS= read -r jar; do
    jars+=("${jar}")
  done < <(discover_jars)
fi

if [[ ${#jars[@]} -eq 0 ]]; then
  echo "FAIL: no jars found under */target even after building. Pass jar paths as arguments."
  exit 1
fi

overall_status=0

# Only meaningful for a whole-tree run; when explicit jars are passed the caller is
# checking artifacts that may not correspond to this working tree at all, such as a
# staged release candidate.
if [[ $# -eq 0 ]]; then
  check_bundled_artifact_ids || overall_status=1
  echo
  check_unmapped_licenses || overall_status=1
  echo
fi

for jar in "${jars[@]}"; do
  if [[ ! -f "${jar}" ]]; then
    echo "FAIL ${jar}: not a file."
    overall_status=1
    continue
  fi

  # original-*.jar is the pre-shade copy the shade plugin leaves behind, it is
  # never published.
  case "$(basename "${jar}")" in
    original-*) continue ;;
  esac

  entries="$(unzip -Z1 "${jar}" | grep -v '/$' || true)"

  # Only consider entries that look like licensing information. Class files that
  # merely contain the word "license" in their name are not interesting here.
  # Deliberately matches the words anywhere in the path, not just at a path
  # boundary: dependencies ship things like META-INF/ASM_LICENSE.txt and
  # META-INF/CLI-LICENSE.txt, which a boundary-anchored pattern would miss.
  # META-INF/maven/** holds the pom.xml and pom.properties Maven embeds for each
  # shaded artifact. They are build descriptors, not licensing information, and
  # they only match the pattern below when an artifact happens to be named after
  # one, as xtable-bundle-notices is.
  candidates="$(printf '%s\n' "${entries}" \
    | grep -vE '\.class$' \
    | grep -vE '^META-INF/maven/' \
    | grep -iE '(licen[cs]e|notice|disclaimer|copying)|(^|/)about_files/' \
    || true)"

  findings=()
  while IFS= read -r entry; do
    [[ -z "${entry}" ]] && continue
    if ! is_allowed_entry "${entry}"; then
      findings+=("${entry}")
    fi
  done < <(printf '%s\n' "${candidates}")

  # Match in the shell rather than piping into "grep -q": grep exits on the first
  # match, the writer then takes SIGPIPE, and under "set -o pipefail" the whole
  # pipeline reports failure. That only shows up on the big shaded jars, where the
  # writer has not finished yet, so it would fail intermittently and only for the
  # bundles.
  missing=()
  if [[ $'\n'${entries}$'\n' != *$'\n'"META-INF/LICENSE"$'\n'* ]]; then
    missing+=("META-INF/LICENSE")
  fi
  if [[ $'\n'${entries}$'\n' != *$'\n'"META-INF/NOTICE"$'\n'* ]]; then
    missing+=("META-INF/NOTICE")
  fi

  if [[ ${#missing[@]} -gt 0 ]]; then
    echo "FAIL $(basename "${jar}"): missing ${missing[*]}."
    overall_status=1
    continue
  fi

  if [[ ${#findings[@]} -gt 0 ]]; then
    echo "FAIL $(basename "${jar}"): licensing information outside the canonical locations:"
    printf '  - %s\n' "${findings[@]}"
    overall_status=1
  else
    echo "OK   $(basename "${jar}"): META-INF/LICENSE, META-INF/NOTICE."
  fi
done

exit "${overall_status}"
